# Generated by Django 2.2.3 on 2019-11-25 19:29

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': (('-name',), 'desc'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('message', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=utils.upload.task_document_path, validators=[utils.validators.validate_file_size, utils.validators.validate_extension])),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'DONE'), (2, 'TODO'), (3, 'TESTED')], default=2)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('priority', models.PositiveIntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high')], default=2)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'my_tasks',
                'ordering': ('name', 'status'),
            },
        ),
    ]
