CATEG_MUSIC = 1
CATEG_LIFESTYLE = 2

BLOG_CATEGORIES = (
    (CATEG_MUSIC, 'MUSIC'),
    (CATEG_LIFESTYLE, 'LIFE STYLE'),
)

TASK_PRIORITY_LOW = 1
TASK_PRIORITY_MEDIUM = 2
TASK_PRIORITY_HIGH = 3
TASK_PRIORITIES = (
    (TASK_PRIORITY_LOW, 'low'),
    (TASK_PRIORITY_MEDIUM, 'medium'),
    (TASK_PRIORITY_HIGH, 'high'),
)

BLOG_PUBLIC = 1
BLOG_PRIVATE = 2
BLOG_TYPES = (
    (BLOG_PUBLIC, 'PUBLIC'),
    (BLOG_PRIVATE, 'PRIVATE'),
)