# Generated by Django 2.2.3 on 2019-11-26 08:20

from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('color', models.PositiveIntegerField(choices=[(1, 'RED'), (2, 'GREEN'), (3, 'BLUE')], default=1)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.upload.article_image_path, validators=[utils.validators.validate_file_size, utils.validators.validate_extension])),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_articles', to='api.Article')),
            ],
            options={
                'verbose_name': 'Fav_artic',
                'verbose_name_plural': 'Fav_artics',
                'db_table': 'my_favorites',
            },
        ),
    ]
