# Generated by Django 2.2.3 on 2019-09-25 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_members',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project_members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='api.Project'),
        ),
    ]
