# Generated by Django 2.2.3 on 2019-12-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_blogcategory_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(null=True, related_name='blogs', to='api.BlogCategory'),
        ),
    ]
