# Generated by Django 2.2.3 on 2019-12-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191204_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='blogs',
            field=models.ManyToManyField(null=True, related_name='categories', to='api.Blog'),
        ),
    ]
