from .views_api import BlogCategoryAPIView, BlogCategoryDetailAPIView
from .view_generic import PostMediafileCreateView, PostCommentCreateView
from .views_viewset import FavoritePostsDetailViewSet, FavoritePostsViewSet, BlogViewSet, PostViewSet